// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// compute_gene_burden
void compute_gene_burden(const std::string& bed_prefix, const std::string& gene_file, const std::string& out_file, int write_buffer_genes);
RcppExport SEXP _StratGWAS_compute_gene_burden(SEXP bed_prefixSEXP, SEXP gene_fileSEXP, SEXP out_fileSEXP, SEXP write_buffer_genesSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bed_prefix(bed_prefixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type gene_file(gene_fileSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< int >::type write_buffer_genes(write_buffer_genesSEXP);
    compute_gene_burden(bed_prefix, gene_file, out_file, write_buffer_genes);
    return R_NilValue;
END_RCPP
}
// compute_burden_windows
void compute_burden_windows(const std::string& bed_prefix, const std::string& out_file, double kb_size, int n_snps_per_window, double target_mac_per_ind, int write_buffer_size, int chunk_size, std::string effects_file, bool write_burden_scores);
RcppExport SEXP _StratGWAS_compute_burden_windows(SEXP bed_prefixSEXP, SEXP out_fileSEXP, SEXP kb_sizeSEXP, SEXP n_snps_per_windowSEXP, SEXP target_mac_per_indSEXP, SEXP write_buffer_sizeSEXP, SEXP chunk_sizeSEXP, SEXP effects_fileSEXP, SEXP write_burden_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type bed_prefix(bed_prefixSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< double >::type kb_size(kb_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_snps_per_window(n_snps_per_windowSEXP);
    Rcpp::traits::input_parameter< double >::type target_mac_per_ind(target_mac_per_indSEXP);
    Rcpp::traits::input_parameter< int >::type write_buffer_size(write_buffer_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< std::string >::type effects_file(effects_fileSEXP);
    Rcpp::traits::input_parameter< bool >::type write_burden_scores(write_burden_scoresSEXP);
    compute_burden_windows(bed_prefix, out_file, kb_size, n_snps_per_window, target_mac_per_ind, write_buffer_size, chunk_size, effects_file, write_burden_scores);
    return R_NilValue;
END_RCPP
}
// compute_burden_weights_blockwise
List compute_burden_weights_blockwise(const std::string& burden_file, int max_neighbors);
RcppExport SEXP _StratGWAS_compute_burden_weights_blockwise(SEXP burden_fileSEXP, SEXP max_neighborsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type burden_file(burden_fileSEXP);
    Rcpp::traits::input_parameter< int >::type max_neighbors(max_neighborsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_burden_weights_blockwise(burden_file, max_neighbors));
    return rcpp_result_gen;
END_RCPP
}
// vb_elastic_net_prs
Rcpp::List vb_elastic_net_prs(const std::string& filename, const SEXP pheno_mat, const Rcpp::NumericVector& maf_all, const Rcpp::IntegerVector& chr_all, double h2, double alpha_param, double p_en, double F_en, int chunk_size, double tol, int max_scans, bool loco, int loco_chr);
RcppExport SEXP _StratGWAS_vb_elastic_net_prs(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP maf_allSEXP, SEXP chr_allSEXP, SEXP h2SEXP, SEXP alpha_paramSEXP, SEXP p_enSEXP, SEXP F_enSEXP, SEXP chunk_sizeSEXP, SEXP tolSEXP, SEXP max_scansSEXP, SEXP locoSEXP, SEXP loco_chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type maf_all(maf_allSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type chr_all(chr_allSEXP);
    Rcpp::traits::input_parameter< double >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_param(alpha_paramSEXP);
    Rcpp::traits::input_parameter< double >::type p_en(p_enSEXP);
    Rcpp::traits::input_parameter< double >::type F_en(F_enSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_scans(max_scansSEXP);
    Rcpp::traits::input_parameter< bool >::type loco(locoSEXP);
    Rcpp::traits::input_parameter< int >::type loco_chr(loco_chrSEXP);
    rcpp_result_gen = Rcpp::wrap(vb_elastic_net_prs(filename, pheno_mat, maf_all, chr_all, h2, alpha_param, p_en, F_en, chunk_size, tol, max_scans, loco, loco_chr));
    return rcpp_result_gen;
END_RCPP
}
// vb_elastic_net_prs_multi
Rcpp::List vb_elastic_net_prs_multi(const std::string& filename, const SEXP pheno_mat, const Rcpp::NumericVector& maf_all, const Rcpp::IntegerVector& chr_all, double h2, double alpha_param, double p_en, double F_en, int chunk_size, double tol, int max_scans, bool loco, int loco_chr);
RcppExport SEXP _StratGWAS_vb_elastic_net_prs_multi(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP maf_allSEXP, SEXP chr_allSEXP, SEXP h2SEXP, SEXP alpha_paramSEXP, SEXP p_enSEXP, SEXP F_enSEXP, SEXP chunk_sizeSEXP, SEXP tolSEXP, SEXP max_scansSEXP, SEXP locoSEXP, SEXP loco_chrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type maf_all(maf_allSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type chr_all(chr_allSEXP);
    Rcpp::traits::input_parameter< double >::type h2(h2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha_param(alpha_paramSEXP);
    Rcpp::traits::input_parameter< double >::type p_en(p_enSEXP);
    Rcpp::traits::input_parameter< double >::type F_en(F_enSEXP);
    Rcpp::traits::input_parameter< int >::type chunk_size(chunk_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< int >::type max_scans(max_scansSEXP);
    Rcpp::traits::input_parameter< bool >::type loco(locoSEXP);
    Rcpp::traits::input_parameter< int >::type loco_chr(loco_chrSEXP);
    rcpp_result_gen = Rcpp::wrap(vb_elastic_net_prs_multi(filename, pheno_mat, maf_all, chr_all, h2, alpha_param, p_en, F_en, chunk_size, tol, max_scans, loco, loco_chr));
    return rcpp_result_gen;
END_RCPP
}
// read_bim_file
List read_bim_file(const std::string& filename);
RcppExport SEXP _StratGWAS_read_bim_file(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_bim_file(filename));
    return rcpp_result_gen;
END_RCPP
}
// read_fam_file
Rcpp::List read_fam_file(const std::string& filename);
RcppExport SEXP _StratGWAS_read_fam_file(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(read_fam_file(filename));
    return rcpp_result_gen;
END_RCPP
}
// compute_maf_all
Rcpp::NumericVector compute_maf_all(const std::string& filename);
RcppExport SEXP _StratGWAS_compute_maf_all(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_maf_all(filename));
    return rcpp_result_gen;
END_RCPP
}
// he
Rcpp::NumericVector he(const Eigen::MatrixXd& genotypes, const Rcpp::NumericVector& pheno);
RcppExport SEXP _StratGWAS_he(SEXP genotypesSEXP, SEXP phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pheno(phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(he(genotypes, pheno));
    return rcpp_result_gen;
END_RCPP
}
// he_multi
Rcpp::NumericMatrix he_multi(const Eigen::MatrixXd& genotypes, const Rcpp::NumericMatrix& pheno);
RcppExport SEXP _StratGWAS_he_multi(SEXP genotypesSEXP, SEXP phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type pheno(phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(he_multi(genotypes, pheno));
    return rcpp_result_gen;
END_RCPP
}
// he_multi_part
Rcpp::NumericMatrix he_multi_part(const std::string& filename, const SEXP pheno_mat, int block_size);
RcppExport SEXP _StratGWAS_he_multi_part(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(he_multi_part(filename, pheno_mat, block_size));
    return rcpp_result_gen;
END_RCPP
}
// he_sliding_window_part
Rcpp::List he_sliding_window_part(const std::string& filename, const SEXP pheno_mat, const IntegerMatrix snp_cat, const CharacterVector cat_names, double window_size, int min_snps, double alpha, Rcpp::Nullable<Rcpp::String> common_filename, int nmcmc, bool se, std::string out_file, int batch_size, int n_threads, int seed, Rcpp::Nullable<Rcpp::NumericVector> weights, Rcpp::Nullable<Rcpp::NumericMatrix> covariates, bool coher);
RcppExport SEXP _StratGWAS_he_sliding_window_part(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP snp_catSEXP, SEXP cat_namesSEXP, SEXP window_sizeSEXP, SEXP min_snpsSEXP, SEXP alphaSEXP, SEXP common_filenameSEXP, SEXP nmcmcSEXP, SEXP seSEXP, SEXP out_fileSEXP, SEXP batch_sizeSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP weightsSEXP, SEXP covariatesSEXP, SEXP coherSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix >::type snp_cat(snp_catSEXP);
    Rcpp::traits::input_parameter< const CharacterVector >::type cat_names(cat_namesSEXP);
    Rcpp::traits::input_parameter< double >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_snps(min_snpsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::String> >::type common_filename(common_filenameSEXP);
    Rcpp::traits::input_parameter< int >::type nmcmc(nmcmcSEXP);
    Rcpp::traits::input_parameter< bool >::type se(seSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type covariates(covariatesSEXP);
    Rcpp::traits::input_parameter< bool >::type coher(coherSEXP);
    rcpp_result_gen = Rcpp::wrap(he_sliding_window_part(filename, pheno_mat, snp_cat, cat_names, window_size, min_snps, alpha, common_filename, nmcmc, se, out_file, batch_size, n_threads, seed, weights, covariates, coher));
    return rcpp_result_gen;
END_RCPP
}
// reml_sliding_window_part
Rcpp::List reml_sliding_window_part(const std::string& filename, const SEXP pheno_mat, const IntegerMatrix snp_cat, const CharacterVector cat_names, double window_size, int min_snps, double alpha, Rcpp::Nullable<Rcpp::String> common_filename, int max_iter, double tol, bool se, std::string out_file, int batch_size, int n_threads, int seed, Rcpp::Nullable<Rcpp::NumericVector> weights, Rcpp::Nullable<Rcpp::NumericMatrix> covariates);
RcppExport SEXP _StratGWAS_reml_sliding_window_part(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP snp_catSEXP, SEXP cat_namesSEXP, SEXP window_sizeSEXP, SEXP min_snpsSEXP, SEXP alphaSEXP, SEXP common_filenameSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP seSEXP, SEXP out_fileSEXP, SEXP batch_sizeSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP weightsSEXP, SEXP covariatesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix >::type snp_cat(snp_catSEXP);
    Rcpp::traits::input_parameter< const CharacterVector >::type cat_names(cat_namesSEXP);
    Rcpp::traits::input_parameter< double >::type window_size(window_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type min_snps(min_snpsSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::String> >::type common_filename(common_filenameSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< bool >::type se(seSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_file(out_fileSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericMatrix> >::type covariates(covariatesSEXP);
    rcpp_result_gen = Rcpp::wrap(reml_sliding_window_part(filename, pheno_mat, snp_cat, cat_names, window_size, min_snps, alpha, common_filename, max_iter, tol, se, out_file, batch_size, n_threads, seed, weights, covariates));
    return rcpp_result_gen;
END_RCPP
}
// computeLDscoresFromBED
DataFrame computeLDscoresFromBED(std::string file_prefix, IntegerVector geno_set);
RcppExport SEXP _StratGWAS_computeLDscoresFromBED(SEXP file_prefixSEXP, SEXP geno_setSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type file_prefix(file_prefixSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type geno_set(geno_setSEXP);
    rcpp_result_gen = Rcpp::wrap(computeLDscoresFromBED(file_prefix, geno_set));
    return rcpp_result_gen;
END_RCPP
}
// linear_gwas
Rcpp::NumericMatrix linear_gwas(const std::string& filename, const SEXP pheno_mat, int block_size, const std::string& out_file);
RcppExport SEXP _StratGWAS_linear_gwas(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP block_sizeSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_gwas(filename, pheno_mat, block_size, out_file));
    return rcpp_result_gen;
END_RCPP
}
// linear_gwas_parallel
Rcpp::NumericMatrix linear_gwas_parallel(const std::string& filename, const SEXP pheno_mat, int block_size, const std::string& out_file);
RcppExport SEXP _StratGWAS_linear_gwas_parallel(SEXP filenameSEXP, SEXP pheno_matSEXP, SEXP block_sizeSEXP, SEXP out_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const SEXP >::type pheno_mat(pheno_matSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type out_file(out_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(linear_gwas_parallel(filename, pheno_mat, block_size, out_file));
    return rcpp_result_gen;
END_RCPP
}
// readBedBlock
Rcpp::IntegerMatrix readBedBlock(std::string filename, int n_ind, int n_snp, int start_ind, int end_ind, int start_snp, int end_snp);
RcppExport SEXP _StratGWAS_readBedBlock(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP, SEXP start_indSEXP, SEXP end_indSEXP, SEXP start_snpSEXP, SEXP end_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_snp(n_snpSEXP);
    Rcpp::traits::input_parameter< int >::type start_ind(start_indSEXP);
    Rcpp::traits::input_parameter< int >::type end_ind(end_indSEXP);
    Rcpp::traits::input_parameter< int >::type start_snp(start_snpSEXP);
    Rcpp::traits::input_parameter< int >::type end_snp(end_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(readBedBlock(filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp));
    return rcpp_result_gen;
END_RCPP
}
// compute_prs
Rcpp::DataFrame compute_prs(const std::string& filename, const Rcpp::CharacterVector& snp_input, const Rcpp::NumericVector& beta_input, int block_size);
RcppExport SEXP _StratGWAS_compute_prs(SEXP filenameSEXP, SEXP snp_inputSEXP, SEXP beta_inputSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type snp_input(snp_inputSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta_input(beta_inputSEXP);
    Rcpp::traits::input_parameter< int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_prs(filename, snp_input, beta_input, block_size));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StratGWAS_compute_gene_burden", (DL_FUNC) &_StratGWAS_compute_gene_burden, 4},
    {"_StratGWAS_compute_burden_windows", (DL_FUNC) &_StratGWAS_compute_burden_windows, 9},
    {"_StratGWAS_compute_burden_weights_blockwise", (DL_FUNC) &_StratGWAS_compute_burden_weights_blockwise, 2},
    {"_StratGWAS_vb_elastic_net_prs", (DL_FUNC) &_StratGWAS_vb_elastic_net_prs, 13},
    {"_StratGWAS_vb_elastic_net_prs_multi", (DL_FUNC) &_StratGWAS_vb_elastic_net_prs_multi, 13},
    {"_StratGWAS_read_bim_file", (DL_FUNC) &_StratGWAS_read_bim_file, 1},
    {"_StratGWAS_read_fam_file", (DL_FUNC) &_StratGWAS_read_fam_file, 1},
    {"_StratGWAS_compute_maf_all", (DL_FUNC) &_StratGWAS_compute_maf_all, 1},
    {"_StratGWAS_he", (DL_FUNC) &_StratGWAS_he, 2},
    {"_StratGWAS_he_multi", (DL_FUNC) &_StratGWAS_he_multi, 2},
    {"_StratGWAS_he_multi_part", (DL_FUNC) &_StratGWAS_he_multi_part, 3},
    {"_StratGWAS_he_sliding_window_part", (DL_FUNC) &_StratGWAS_he_sliding_window_part, 17},
    {"_StratGWAS_reml_sliding_window_part", (DL_FUNC) &_StratGWAS_reml_sliding_window_part, 17},
    {"_StratGWAS_computeLDscoresFromBED", (DL_FUNC) &_StratGWAS_computeLDscoresFromBED, 2},
    {"_StratGWAS_linear_gwas", (DL_FUNC) &_StratGWAS_linear_gwas, 4},
    {"_StratGWAS_linear_gwas_parallel", (DL_FUNC) &_StratGWAS_linear_gwas_parallel, 4},
    {"_StratGWAS_readBedBlock", (DL_FUNC) &_StratGWAS_readBedBlock, 7},
    {"_StratGWAS_compute_prs", (DL_FUNC) &_StratGWAS_compute_prs, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_StratGWAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
