// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// he
Rcpp::NumericVector he(const Eigen::MatrixXd& genotypes, const Rcpp::NumericVector& pheno);
RcppExport SEXP _StratGWAS_he(SEXP genotypesSEXP, SEXP phenoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type genotypes(genotypesSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type pheno(phenoSEXP);
    rcpp_result_gen = Rcpp::wrap(he(genotypes, pheno));
    return rcpp_result_gen;
END_RCPP
}
// readBedBlock
IntegerMatrix readBedBlock(std::string filename, int n_ind, int n_snp, int start_ind, int end_ind, int start_snp, int end_snp);
RcppExport SEXP _StratGWAS_readBedBlock(SEXP filenameSEXP, SEXP n_indSEXP, SEXP n_snpSEXP, SEXP start_indSEXP, SEXP end_indSEXP, SEXP start_snpSEXP, SEXP end_snpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< int >::type n_ind(n_indSEXP);
    Rcpp::traits::input_parameter< int >::type n_snp(n_snpSEXP);
    Rcpp::traits::input_parameter< int >::type start_ind(start_indSEXP);
    Rcpp::traits::input_parameter< int >::type end_ind(end_indSEXP);
    Rcpp::traits::input_parameter< int >::type start_snp(start_snpSEXP);
    Rcpp::traits::input_parameter< int >::type end_snp(end_snpSEXP);
    rcpp_result_gen = Rcpp::wrap(readBedBlock(filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_StratGWAS_he", (DL_FUNC) &_StratGWAS_he, 2},
    {"_StratGWAS_readBedBlock", (DL_FUNC) &_StratGWAS_readBedBlock, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_StratGWAS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
