# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_bim_file <- function(filename) {
    .Call(`_StratGWAS_read_bim_file`, filename)
}

read_fam_file <- function(filename) {
    .Call(`_StratGWAS_read_fam_file`, filename)
}

he <- function(genotypes, pheno) {
    .Call(`_StratGWAS_he`, genotypes, pheno)
}

he_multi <- function(genotypes, pheno) {
    .Call(`_StratGWAS_he_multi`, genotypes, pheno)
}

he_multi_part <- function(filename, pheno_mat, block_size) {
    .Call(`_StratGWAS_he_multi_part`, filename, pheno_mat, block_size)
}

computeLDscoresFromBED <- function(file_prefix, n_ind, n_snp) {
    .Call(`_StratGWAS_computeLDscoresFromBED`, file_prefix, n_ind, n_snp)
}

linear_gwas <- function(filename, pheno_file, out_file, n_inds, n_snps, block_size) {
    .Call(`_StratGWAS_linear_gwas`, filename, pheno_file, out_file, n_inds, n_snps, block_size)
}

readBedBlock <- function(filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp) {
    .Call(`_StratGWAS_readBedBlock`, filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp)
}

