# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

he <- function(genotypes, pheno) {
    .Call('_StratGWAS_he', PACKAGE = 'StratGWAS', genotypes, pheno)
}

readBedBlock <- function(filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp) {
    .Call('_StratGWAS_readBedBlock', PACKAGE = 'StratGWAS', filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp)
}

