# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_gene_burden <- function(bed_prefix, gene_file, out_file, write_buffer_genes = 500L) {
    invisible(.Call(`_StratGWAS_compute_gene_burden`, bed_prefix, gene_file, out_file, write_buffer_genes))
}

vb_elastic_net_prs <- function(filename, pheno_mat, maf_all, chr_all, h2, alpha_param, p_en, F_en, chunk_size, tol, max_scans, loco, loco_chr) {
    .Call(`_StratGWAS_vb_elastic_net_prs`, filename, pheno_mat, maf_all, chr_all, h2, alpha_param, p_en, F_en, chunk_size, tol, max_scans, loco, loco_chr)
}

read_bim_file <- function(filename) {
    .Call(`_StratGWAS_read_bim_file`, filename)
}

read_fam_file <- function(filename) {
    .Call(`_StratGWAS_read_fam_file`, filename)
}

he <- function(genotypes, pheno) {
    .Call(`_StratGWAS_he`, genotypes, pheno)
}

he_multi <- function(genotypes, pheno) {
    .Call(`_StratGWAS_he_multi`, genotypes, pheno)
}

he_multi_part <- function(filename, pheno_mat, block_size) {
    .Call(`_StratGWAS_he_multi_part`, filename, pheno_mat, block_size)
}

computeLDscoresFromBED <- function(file_prefix, geno_set) {
    .Call(`_StratGWAS_computeLDscoresFromBED`, file_prefix, geno_set)
}

linear_gwas <- function(filename, pheno_mat, block_size, out_file) {
    .Call(`_StratGWAS_linear_gwas`, filename, pheno_mat, block_size, out_file)
}

linear_gwas_parallel <- function(filename, pheno_mat, block_size, out_file) {
    .Call(`_StratGWAS_linear_gwas_parallel`, filename, pheno_mat, block_size, out_file)
}

readBedBlock <- function(filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp) {
    .Call(`_StratGWAS_readBedBlock`, filename, n_ind, n_snp, start_ind, end_ind, start_snp, end_snp)
}

compute_prs <- function(filename, snp_input, beta_input, block_size) {
    .Call(`_StratGWAS_compute_prs`, filename, snp_input, beta_input, block_size)
}

